// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrintFlow.Api.Data;

#nullable disable

namespace PrintFlow.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310232736_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("PrintFlow.Api.Models.Filamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Peso")
                        .HasColumnType("REAL");

                    b.Property<float>("Preco")
                        .HasColumnType("REAL");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Total")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Filamentos");
                });

            modelBuilder.Entity("PrintFlow.Api.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<float>("Custo")
                        .HasColumnType("REAL");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("FilamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("TempoHoras")
                        .HasColumnType("REAL");

                    b.Property<float>("Venda")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FilamentoId");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("PrintFlow.Api.Models.Projeto", b =>
                {
                    b.HasOne("PrintFlow.Api.Models.Filamento", "Filamento")
                        .WithMany()
                        .HasForeignKey("FilamentoId");

                    b.Navigation("Filamento");
                });
#pragma warning restore 612, 618
        }
    }
}
